default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: product_teardown_app_development

test:
  <<: *default
  database: product_teardown_app_test
